name: Deploy Branch

on:
  workflow_dispatch:
    inputs:
      branchToDeploy:
        description: 'Branch name to deploy'
        required: true
      environment:
        description: 'Salesforce environment where to execute the full deploy'
        type: environment
      testLevel:
        description: 'Test level to run'
        required: true
        default: 'NoTestRun'
        type: choice
        options:
        - NoTestRun
        - RunLocalTests
        - RunSpecifiedTests
        - RunAllTestsInOrg
      testClassToRun:
        description: 'Comma separeted list of test class to run in case of RunSpecifiedTests'
      description:
        description: 'Description of the changes in the PR'

jobs:
  Deploy_Branch:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # Set Variables
      - run: |
          echo "env: $ENV"
        env:
          BRANCH_TO_DEPLOY: ${{ inputs.branchToDeploy }}
          ENV: ${{ inputs.environment }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true
      # Install SFDX
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
          
      # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
      - name: 'Installing sfdx git delta'
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Authenticate JWT
        run: |
          echo "${{ secrets.SERVER_KEY }}" > SERVER_KEY.key
          sfdx auth:jwt:grant --client-id ${{ vars.CLIENT_ID }} --jwt-key-file SERVER_KEY.key --username ${{ vars.USERNAME }} --instance-url https://login.salesforce.com

      - name: Validate
        if: ${{ success() }}
        run: sfdx force:source:deploy -p ./force-app/main/default --testlevel ${{ inputs.testLevel }} --runtests "${{ inputs.testClassToRun }}" --targetusername ${{ vars.USERNAME }} --json --loglevel fatal