# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]
    paths:
      - 'force-app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # run workflow only from dev branch
    if: github.head_ref == 'dev'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout to dev
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 2
      - name: Checkout to master
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true

      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version

      - name: Install sfpowerkit
        run: echo 'y' | npx sfdx plugins:install sfpowerkit

      - name: 'Populate auth file with SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.SFDX_SECRETKEY }} > SFDX_QA'

      - name: 'Authenticate against dev hub'
        run: sfdx force:auth:sfdxurl:store -f SFDX_QA -s -a MyDev

      # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
      - name: 'Installing sfdx git delta'
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Create delta
        run: |
          mkdir incremental
          sfdx sgd:source:delta -W --output incremental/ --to "HEAD" --from "HEAD^" -s force-app/**

      # - name: Create code artifact backup dev
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: code-artifact-backup-dev
      #     path: force-app/main/default

      - name: Create incremental package
        uses: actions/upload-artifact@v3
        with:
          name: code-artifact
          path: incremental

      - uses: actions/download-artifact@v3
        with:
          name: code-artifact
          path: code-artifact

      - name: Validate
        if: ${{ success() }}
        run: sfdx force:source:deploy -x ./incremental/package/package.xml --postdestructivechanges ./incremental/destructiveChanges/destructiveChanges.xml -l RunLocalTests -u MyDev --json --loglevel fatal

      - name: Set current date
        if: ${{ success() }}
        run: echo "DATE=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV

      - name: Create backup release from prod
        if: ${{ success() }}
        uses: ncipollo/release-action@v1
        with:
          tag: backup-prod-${{ env.DATE }}
