# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]
    # pull_request:
    # branches: [ master ]
    paths:
      - "force-app/**"
  # push:
    # branches: [master]
    # pull_request:
    # branches: [ master ]
    # paths:
      # - "force-app/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14"
          check-latest: true

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Install Salesforce CLI
      # - name: Install Salesforce CLI
      #   run: |
      #     wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      #     mkdir sfdx-cli
      #     tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
      #     ./sfdx-cli/install
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core

      - name: "Populate auth file with SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.SFDX_SECRETKEY }} > SFDX_QA"

      - name: "Authenticate against dev hub"
        run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_QA -s -a MyDev

      # - name: Authenticate to DevOrg
      #   run: |
      #     sfdx auth:sfdxurl:store -f {{secret.SFDX_SECRETKEY}} -s -a MyDev

      # - name: Run Apex test
        # run: 
          # node_modules/sfdx-cli/bin/run force:apex:test:run --resultformat tap --codecoverage -c -r human

      - name: Deploy check
        id: DeployCheck
        if: github.event_name == 'pull_request'
        run:
          node_modules/sfdx-cli/bin/run force:mdapi:deploy -c -f ./deployChanges/unpackaged.zip -l RunLocalTests -u MyDev --json --loglevel fatal
      - name: Deploy source
        id: Deploy
        if: github.event_name == 'push'
        run:
          node_modules/sfdx-cli/bin/run force:mdapi:deploy -f ./deployChanges/unpackaged.zip -l RunLocalTests -u MyDev --json --loglevel fatal
