name: Open PR Incremental

on:
  workflow_dispatch:
    inputs:
      from:
        description: 'From branch of the PR'
        required: true
      to:
        description: 'To branch of the PR'
        required: true
      environment:
        description: 'test run Salesforce environment'
        type: environment
      testLevel:
        description: 'Test level to run'
        required: true
        default: 'NoTestRun'
        type: choice
        options:
        - NoTestRun
        - RunLocalTests
        - RunSpecifiedTests
        - RunAllTestsInOrg
      testClassToRun:
        description: 'Comma separeted list of test class to run in case of RunSpecifiedTests'
      description:
        description: 'Description of the changes in the PR'

jobs:
  Open-PR-Incremental:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # Set Variables
      - run: |
          echo "from branch: $FROM"
          echo "to branch: $TO"
          echo "env: $ENV"
          echo "username: ${{ vars.USERNAME }}"
        env:
          FROM: ${{ inputs.from }}
          TO: ${{ inputs.to }}
          ENV: ${{ inputs.environment }}
          TESTCLASSVALUE: ${{ inputs.testLevel == 'RunSpecifiedTests' }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true
      # Install SFDX
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
          
      # install SFDX-Git-Delta plugin - https://github.com/scolladon/sfdx-git-delta
      - name: 'Installing sfdx git delta'
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      - name: Authenticate JWT
        run: |
          echo "${{ secrets.SERVER_KEY }}" > SERVER_KEY.key
          sfdx auth:jwt:grant --client-id ${{ vars.CLIENT_ID }} --jwt-key-file SERVER_KEY.key --username ${{ vars.USERNAME }} --instance-url https://login.salesforce.com

      - name: Create delta
        run: |
          mkdir incremental
          sfdx sgd:source:delta -W --generate-delta --output incremental/ --to origin/${{ inputs.from }} --from origin/${{ inputs.to }} -s force-app/**
      
      - name: Create incremental package
        uses: actions/upload-artifact@v3
        with:
          name: code-artifact
          path: incremental

      - uses: actions/download-artifact@v3
        with:
          name: code-artifact
          path: code-artifact

      - name: Calculate test class to run
        run: |
          if ${TESTCLASSVALUE} == true
          then
            echo " --runtests "${{ inputs.testClassToRun }}" "
            echo "testClass=--tests "${{ inputs.testClassToRun }}" " >> $GITHUB_ENV
            echo "specific classes to run"
          else
            echo "testClass=" >> $GITHUB_ENV
            echo "no specific classes to run"
          fi

      - name: checkout branch
        run: git checkout ${{ inputs.from }}

      # Install SFDX scanner
      - name: 'Installing SFDX scanner'
        run: sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run Code Scan
        run: sfdx scanner:run --target ./force-app/main/default --format csv

      - name: Validate
        if: ${{ success() }}
        run: sfdx project deploy start --dry-run -x ./incremental/package/package.xml --test-level ${{ inputs.testLevel }} ${{ env.testClass }} --target-org ${{ vars.USERNAME }}

      - name: Automatically open pull request
        if: ${{ success() }}
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ inputs.from }}
          target_branch: ${{ inputs.to }}
          title: "AUTOM-${{ inputs.from }}"
          template: ""
          body: |
            **Automated pull request**
            ${{ inputs.description }}
          reviewer: ""
          assignee: ""
          label: ""
          milestone: ""
          old_string: "<!-- Add your description here -->"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: false
