# This is a basic workflow to help you get started with Actions

name: pr-validation-master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]
    # pull_request:
    # branches: [ master ]
    paths:
      - "force-app/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout to master
        uses: actions/checkout@v3
        with:
          ref: master 

      - name: Set sha on master
        run: echo "sha_prod=${{ github.head.sha }}" >> $GITHUB_ENV

      - name: Checkout to dev
        uses: actions/checkout@v3
        with:
          ref: dev 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14"
          check-latest: true

      - name: Check Event Name
        run: echo ${{ github.event_name }}

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core

      - name: Install sfpowerkit
        run: echo 'y' | npx sfdx plugins:install sfpowerkit

      - name: "Populate auth file with SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.SFDX_SECRETKEY }} > SFDX_QA"

      - name: "Authenticate against dev hub"
        run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_QA -s -a MyDev

      - name: Create Diff Commit
        run: node_modules/sfdx-cli/bin/run sfpowerkit:project:diff -d incremental -p ./force-app/main/default --revisionfrom ${{ github.event.pull_request.head.sha }} --revisionto ${{ env.sha_prod }} -x

      # - name: Deploy source
      #   id: CheckDeploySource
      #   if: github.event.pull_request.opened == true
      #   run:
      #     node_modules/sfdx-cli/bin/run force:source:deploy -p -c -l RunLocalTests -u MyDev --json --loglevel fatal

      - name: Create code artifact backup
        uses: actions/upload-artifact@v3
        with:
          name: code-artifact-backup
          path: force-app/main/default

      - name: Create code artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-artifact
          path: incremental

      - name: Validate
        if: ${{ success() }}
        run: node_modules/sfdx-cli/bin/run force:source:deploy -p ./code-artifact -c -l RunLocalTests -u MyDev --json --loglevel fatal